### ISSUE TITLE
Wrapping text within columns

### ISSUE THREAD

**Issue by jokroese** [rudymatela/concise-cheat-sheets#3]
Some of the lines I would like to include are slightly longer than the width of the columns. Automatically, they continue outside the column borders. I would like to wrap them within a column.

#### Example of default behaviour
```tex
\begin{ldesc}
	\li[Example] this is a long line that I would like to wrap but currently goes outside the column
\end{ldesc}
```
![screenshot 2018-10-31 at 14 06 22](https://user-images.githubusercontent.com/7649772/47809190-bb86e900-dd16-11e8-919c-6ffe2200e8eb.png)

#### Example of what I would like to do
I would like the text to wrap. I can do it manually using
```tex
\begin{ldesc}
	\li[Example] this is a long line that I would like to wrap \li that wraps
\end{ldesc}
```
![screenshot 2018-10-31 at 14 11 20](https://user-images.githubusercontent.com/7649772/47809284-de190200-dd16-11e8-8a23-50fc7e4bdacb.png)

#### Problem
When a longer definition is added to the left-hand side, it throws off the (previously accurate) formatting.
```tex
\begin{ldesc}
	\li[Example]      this is a long line that I would like to wrap \li
	that wraps
	\li[Longer example title]
\end{ldesc}
```
![screenshot 2018-10-31 at 14 24 21](https://user-images.githubusercontent.com/7649772/47810047-bdea4280-dd18-11e8-8d07-b9b67a0b66c0.png)

#### Question
How can I automatically wrap a line within a column?

**Comment by rudymatela** [comment]
@joekroese The `ldesc` environment is admitedly a hack and has limitations.  It currently has no support for automatically breaking lines. Internally it actually generates a `tabular` environment.

You could achieve what you describe by [using tabular directly and a `p` typed column](https://en.wikibooks.org/wiki/LaTeX/Tables#The_tabular_environment):

```
\begin{tabular}{p{0.4\columnwidth}p{0.5\columnwidth}}
bla                                         & ble \\
the quick brown fox jumps over the lazy dog & some other long text that will automatically wrap \\
something                                   & something something something something something \\
\end{tabular}
```

![auto-wrapping](https://user-images.githubusercontent.com/3999598/47814640-fe53bb80-dd2c-11e8-9b44-f74dd7344f6a.png)


You can of course play with the proportion between the columns (here I've used `\hline`s to make it clearer where every cell ends):

```
\begin{tabular}{p{0.3\columnwidth}p{0.6\columnwidth}}
bla                                         & ble \\
the quick brown fox jumps over the lazy dog & some other long text that will automatically wrap \\
something                                   & something something something something something \\
\end{tabular}
```

![auto-wrapping-2](https://user-images.githubusercontent.com/3999598/47814801-60acbc00-dd2d-11e8-8807-c79b176ae37b.png)

I'd recommend keeping the sum as `0.9\columnwidth` or less otherwise you may run over the column division:
* 0.2 + 0.7;
* 0.3 + 0.6;
* 0.4 + 0.5;
* 0.25 + 0.65;
* ...
